name: .NET Core

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    
    - name: listen archives
      run : ls -la
    - name: Install dependencies
      run: dotnet restore formando-devs-api
    - name: Build
      run: dotnet build formando-devs-api --configuration Release --no-restore
    - name: Test
      run: dotnet test formando-devs-test --no-restore --verbosity normal
