name: test aws cli

on: 
  push:
    branch: main
    
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps: 
     - name: install aws cli
       run: |
        aws configure ${{ secrets.AWS_ACCESS_KEY_ID }}

      
     - name : check 
       run: aws configure list 
        
        
