name: test aws cli

on: 
  push:
    branch: main
    
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps: 
     - name: install aws cli
       run: |
        aws configure list
        aws configure ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} us-east-2 none
        aws configure list
        
