name: test aws cli

on: 
  push:
    branch: main
    
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps: 
     - name: install aws cli
       run: |
        aws cli list
        echo " aws cli ok"
